CREATE TABLE saved (
  id integer primary key generated by default as identity, 
  coffee_bean_id INTEGER REFERENCES coffee_beans(id) ON DELETE CASCADE NOT NULL,
  user_id INTEGER REFERENCES filter_users(id) ON DELETE CASCADE NOT NULL,
  UNIQUE (coffee_bean_id, user_id)
);

